Train:
  VindrMammoDataset:
    image_dir: data/vindr-mammo/png_images/
    anno_path: data/vindr-mammo/finding_annotations.csv
    split: train

Test:
  VindrMammoDataset:
    image_dir: data/vindr-mammo/png_images/
    anno_path: data/vindr-mammo/finding_annotations.csv
    split: test



